ngsild operator for scorpio integration
smartfog/fogflow pull request #156
Opened 2020-12-21 17:30 UTC by Neeraj-Nec

add operator for scropio broker integration

2020-12-23 07:16 UTC, naveennec requested changes

2020-12-26 15:52 UTC, Neeraj-Nec commented on application/operator/NGSI-LD-operator/scorpioOperator/function.py
> +ctxELement = {}
done

2021-01-08 15:30 UTC, showersky approved these changes

2021-01-08 15:31 UTC, merged

2021-01-09 01:14 UTC, Neeraj-Nec commented on application/operator/NGSI-LD-operator/scorpioOperator/main.py
> -    fogflow.handleEntity(contextObjs, createRequest, updateRequest, appendRequest)
The above three api is related to Scorpio broker .