Test topology
smartfog/fogflow pull request #290
Opened 2021-07-23 05:15 UTC by Neeraj-Nec

Resolve issue #289

2021-07-25 05:48 UTC, naveennec requested changes

2021-07-27 03:51 UTC, Neeraj-Nec commented on broker/thinBroker.go
> +	fmt.Println("Notification comming from anather broker")
resolved

2021-07-27 03:51 UTC, Neeraj-Nec commented on broker/thinBroker.go
> +	fmt.Println("Notification comming from anather broker")
Resolved

2021-07-27 04:06 UTC, naveennec approved these changes

2021-07-27 04:13 UTC, merged