Use case issue
smartfog/fogflow pull request #382
Opened 2022-03-15 07:37 UTC by Neeraj-Nec

Correct NGSILD usecase

2022-03-15 08:20 UTC, showersky commented
It looks good. If you have already tested those NGSI-LD applications, I can merge this PR and validate it from my side.

2022-03-15 08:55 UTC, Aniket-NEC commented
@showersky I have tested the use-cases and they work fine. 

> I can merge this PR and validate it from my side.

Yes, it would be great if you could merge this pull request. I will soon raise a PR for updated tutorial for all the use-cases. 
Thank you.

2022-03-25 06:54 UTC, naveennec requested changes

2022-03-25 06:54 UTC, naveennec commented on common/ngsi/ngsiclient.go
> +	req.Header.Add("Link", "<https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld>; rel=\"http://www.w3.org/ns/json-ld#context\"; type=\"application/ld+json\"")
please check it as currently we don't support 1.3 and correct the extension.

2022-03-25 06:54 UTC, naveennec commented on doc/en/source/ngsildbasediotintegration.rst
> +		  -H 'Link: <https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld>; rel="https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"; type="application/ld+json"' \
Check everywhere 1.3 is not more supported by FogFlow , it should not be there.

2022-04-03 12:40 UTC, merged